version: '3'

services:
  youtube_downloader:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_SECRET_KEY=your-secret-key
      - DOWNLOAD_DIRECTORY=/app/downloads
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5